version: 2

builds:
  - main: .
    binary: td
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
  - main: .
    binary: td
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - CHANGELOG.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
